spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          search-locations: classpath:\config

server:
  port: 8888
